version: "3"

services:
  taskhub:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
        - PORT=3000
        - DATABASE_URL=mysql://root:root@db:3306/database
        - NEXTAUTH_SECRET=secret
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/TaskHub
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  db_data:
